In [2]:
import numpy as np

In [4]:
#creating single dimension array
a = np.array([1,3,23,45,2])

In [5]:
b = np.array([34,45,5,6,7])

In [6]:
a

array([ 1,  3, 23, 45,  2])

In [7]:
b

array([34, 45,  5,  6,  7])

In [9]:
#creating a 2D array
x = np.array([[1,34],[3,45],[23,5],[45,6],[2,7]])

In [10]:
x


array([[ 1, 34],
       [ 3, 45],
       [23,  5],
       [45,  6],
       [ 2,  7]])

In [12]:
x[0][1]

34

In [13]:
x[0:2]

array([[ 1, 34],
       [ 3, 45]])

In [14]:
x+3

array([[ 4, 37],
       [ 6, 48],
       [26,  8],
       [48,  9],
       [ 5, 10]])

In [15]:
x*2

array([[ 2, 68],
       [ 6, 90],
       [46, 10],
       [90, 12],
       [ 4, 14]])

In [16]:
x**3

array([[    1, 39304],
       [   27, 91125],
       [12167,   125],
       [91125,   216],
       [    8,   343]])

In [17]:
x.shape

(5, 2)

In [20]:
y = x.reshape(2,5)
y

array([[ 1, 34,  3, 45, 23],
       [ 5, 45,  6,  2,  7]])

In [24]:
#only columns
y[:,1]

array([34, 45])

In [3]:
z = np.zeros((5,5))
z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [4]:
z = np.ones((5,5), dtype="int32")

In [6]:
z

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int32)

In [12]:
np.add(x,x)

array([[ 2, 68],
       [ 6, 90],
       [46, 10],
       [90, 12],
       [ 4, 14]])

In [14]:
x/25

array([[0.04, 1.36],
       [0.12, 1.8 ],
       [0.92, 0.2 ],
       [1.8 , 0.24],
       [0.08, 0.28]])