In [7]:
from sklearn import tree
from sklearn import datasets

In [4]:
for i in dir(datasets):
    if 'iris' in i:
        print(i)

load_iris


In [5]:
data = [i for i in dir(datasets) if 'iris' in i]

In [6]:
data

['load_iris']

In [8]:
iris=datasets.load_iris()

In [9]:
#inside data
dir(iris)

['DESCR', 'data', 'feature_names', 'filename', 'target', 'target_names']

In [10]:
#OR
#from sklearn.datasets import load_iris

In [11]:
iris.DESCR

'.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n                \n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n    ============== ==== =

In [12]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [14]:
feature_attributes = iris.feature_names
feature_attributes

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [17]:
#actual data with 4 columns and 150 rows, 50 of each flower
features=iris.data
features
features.shape

(150, 4)

In [18]:
type(features)

numpy.ndarray

In [19]:
#actual answer
label=iris.target

In [20]:
iris.target.shape

(150,)

In [21]:
#features[0:50]
label[0:50]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0])

In [22]:
sl=features[:,0]
sw=features[:,1]
pl=features[:,2]
pw=features[:,3]

In [23]:
sl.shape

(150,)

In [24]:
#plotting data with matplotlib
import matplotlib.pyplot as plt
plt.scatter(sl,sw,label='SWL')
plt.scatter(sl,pl,label='SPL')
plt.scatter(sl,pw,label='SLPW')
plt.scatter(pl,pw,label='PLPW')
plt.legend()
plt.show()

<Figure size 640x480 with 1 Axes>

In [25]:
#Dividing data
from sklearn.model_selection import train_test_split
data_split=train_test_split(features,label)
data_split=train_test_split(features,label,test_size=0.2) #20% for training

In [26]:
#train_x,train_y,test=data_split
train_features,test_features,train_label,test_label=data_split
#trainQ,test Q, train A, test A

In [27]:
#calls classifier
from sklearn import tree
clf=tree.DecisionTreeClassifier()

In [28]:
#training data
trained=clf.fit(train_features,train_label)

In [29]:
#now prediction
predicted=trained.predict(test_features)
predicted

array([2, 0, 1, 0, 2, 0, 1, 2, 2, 1, 2, 0, 1, 0, 1, 1, 0, 2, 1, 1, 2, 2,
       0, 1, 1, 1, 1, 2, 0, 2])

In [30]:
test_label

array([2, 0, 1, 0, 2, 0, 1, 1, 2, 1, 2, 0, 1, 0, 1, 1, 0, 2, 1, 1, 2, 2,
       0, 1, 1, 1, 1, 2, 0, 2])

In [ ]:
from sklearn.metrics import accuracy_s