In [2]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier

In [5]:
df=pd.read_csv('social.csv')
df

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
5    15728773    Male   27            58000          0
6    15598044  Female   27            84000          0
7    15694829  Female   32           150000          1
8    15600575    Male   25            33000          0
9    15727311  Female   35            65000          0
10   15570769  Female   26            80000          0
11   15606274  Female   26            52000          0
12   15746139    Male   20            86000          0
13   15704987    Male   32            18000          0
14   15628972    Male   18            82000          0
15   15697686    Male   29            80000          0
16   15733883    Male   47            25000          1
17   15617482    Male   45            26000          1
18   15704583    Male   46            28000          1
19   15621083  Female   48            29000          1
20   15649487    Male   45            22000          1
21   15736760  Female   47            49000          1
22   15714658    Male   48            41000          1
23   15599081  Female   45            22000          1
24   15705113    Male   46            23000          1
25   15631159    Male   47            20000          1
26   15792818    Male   49            28000          1
27   15633531  Female   47            30000          1
28   15744529    Male   29            43000          0
29   15669656    Male   31            18000          0
..        ...     ...  ...              ...        ...
370  15611430  Female   60            46000          1
371  15774744    Male   60            83000          1
372  15629885  Female   39            73000          0
373  15708791    Male   59           130000          1
374  15793890  Female   37            80000          0
375  15646091  Female   46            32000          1
376  15596984  Female   46            74000          0
377  15800215  Female   42            53000          0
378  15577806    Male   41            87000          1
379  15749381  Female   58            23000          1
380  15683758    Male   42            64000          0
381  15670615    Male   48            33000          1
382  15715622  Female   44           139000          1
383  15707634    Male   49            28000          1
384  15806901  Female   57            33000          1
385  15775335    Male   56            60000          1
386  15724150  Female   49            39000          1
387  15627220    Male   39            71000          0
388  15672330    Male   47            34000          1
389  15668521  Female   48            35000          1
390  15807837    Male   48            33000          1
391  15592570    Male   47            23000          1
392  15748589  Female   45            45000          1
393  15635893    Male   60            42000          1
394  15757632  Female   39            59000          0
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [7]:
#picking features
features=df.iloc[:,:-1].values    #it will change df into numpy array
features

array([[15624510, 'Male', 19, 19000],
       [15810944, 'Male', 35, 20000],
       [15668575, 'Female', 26, 43000],
       ...,
       [15654296, 'Female', 50, 20000],
       [15755018, 'Male', 36, 33000],
       [15594041, 'Female', 49, 36000]], dtype=object)

In [9]:
label=df.iloc[:,-1].values
label

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,

In [11]:
actual_features=features[:,2:4]
actual_features.shape

(400, 2)

In [12]:
#feature scaling 
from sklearn.preprocessing import StandardScaler
f_sc=StandardScaler()

In [14]:
#now training and training data sep
from sklearn.model_selection import train_test_split
train_x,test_x,train_y,test_y=train_test_split(actual_features,label,test_size=0.2)

In [15]:
# here apply feature scaling 
final_train=f_sc.fit_transform(train_x) #takes maximum of training data

In [16]:
final_train

array([[ 1.01099041,  1.71571081],
       [ 0.14571481, -0.28064897],
       [-1.77711985, -1.42142599],
       [-0.91184425,  0.37529781],
       [ 0.43414001,  2.22906047],
       [ 0.33799828,  0.03306471],
       [ 0.43414001,  0.11862299],
       [ 1.10713215,  0.51789494],
       [-0.71956078, -1.53550369],
       [ 0.43414001, -0.48028495],
       [ 0.14571481,  1.80126908],
       [ 0.04957308,  0.26122011],
       [-1.29641118, -0.36620725],
       [-0.33499385,  1.17384173],
       [-0.91184425, -0.33768782],
       [-0.04656865,  0.23270069],
       [-0.71956078,  1.0312446 ],
       [-1.87326158, -0.7654792 ],
       [ 1.10713215, -0.16657127],
       [ 0.81870695,  1.31643885],
       [ 1.10713215, -1.22179001],
       [-0.14271039,  1.34495828],
       [-0.81570252,  0.34677839],
       [-0.14271039, -0.22361012],
       [ 0.04957308, -0.59436265],
       [ 0.43414001,  1.05976402],
       [ 0.14571481,  0.71753092],
       [-0.14271039, -0.3091684 ],
       [-0.14271039,

In [17]:
#testing data 
final_test=f_sc.transform(test_x)   # only testing data

In [18]:
final_test

array([[ 1.20327388, -0.99363461],
       [-1.00798598, -0.48028495],
       [-0.04656865,  0.26122011],
       [ 0.91484868,  0.97420575],
       [ 1.49169908,  0.03306471],
       [-1.00798598,  0.37529781],
       [ 1.49169908,  2.05794391],
       [-1.29641118, -1.47846484],
       [-1.10412772, -1.53550369],
       [-0.23885212, -0.59436265],
       [-1.68097812,  0.43233666],
       [-1.68097812, -1.36438714],
       [-1.00798598,  0.71753092],
       [-0.23885212, -0.67992093],
       [ 0.14571481,  0.23270069],
       [-0.23885212, -1.25030943],
       [ 1.39555735, -0.93659576],
       [ 1.78012428,  1.77274966],
       [ 0.91484868, -1.16475116],
       [ 0.72256521, -1.27882886],
       [ 0.33799828,  0.03306471],
       [ 0.24185655,  0.11862299],
       [ 0.33799828,  0.23270069],
       [ 1.97240775,  0.68901149],
       [ 0.72256521, -1.39290656],
       [-0.33499385, -1.30734829],
       [-0.23885212,  0.03306471],
       [-0.91184425, -0.96511518],
       [-0.14271039,

In [19]:
#calling RandomForest Classifier
clf=RandomForestClassifier(n_estimators=30, criterion='entropy')

In [21]:
from sklearn.metrics import accuracy_score

In [22]:
trained=clf.fit(train_x,train_y)

In [24]:
predicted=trained.predict(test_x)
predicted

array([1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1])

In [25]:
test_y

array([1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1,
       1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1])

In [26]:
accuracy_score(predicted,test_y)

0.9125